### PR TITLE
Created Chicago Template

### PR DESCRIPTION
**Pull request by ejzim**
Created a Chicago theme based on the University of Chicago thesis template for economics. Although there is no formal centralized format, most departments use something similar to this for theses at all levels.

### CODE REVIEW

**Comment by suchow** [comment]
Hi, thanks for this!

A few questions and requests:

1. Can you move the `Chicago` directory into `assets/schools/`?

2. Did you intend not to include a references section and the colophon?

3. Is the honors BA thesis guidelines the best document you can find?

**Comment by ejzim** [comment]
Hi Jordan,
1. Not a problem. Done.
2. I did not realize you wanted this. For citations, you would just use the bibtex style “chicago”. I have included that in the readme. Regarding the colophon, I don’t see it in the Harvard folder, but have no problem putting it in if you like.
3. Yes, this is the best I can find. Chicago doesn’t have a centralized thesis formatting document like Harvard. However, I have seen dozens of theses spanning bachelors to PhD and in a few departments, and the cover pages are pretty similar.

Best, cheers, etc -Evan via iPhone
On Mon, Apr 18, 2016 at 23:10, Jordan Suchow <notifications@github.com> wrote:
Hi, thanks for this!

A few questions and requests:

 1. Can you move the Chicago directory into assets/schools/ ?
    
    
 2. Did you intend not to include a references section and the colophon?
    
    
 3. Is the honors BA thesis guidelines the best document you can find?

**Comment by ejzim** [comment]
added chicago theme

**Comment by michaelpacer** [comment]
@ejzim 

It looks like [this page at the Chicago library site for dissertations](https://www.lib.uchicago.edu/research/scholar/phd/students/checklist/) links to this [pdf on formatting requirements from 2011](https://www.lib.uchicago.edu/documents/788/booklet2011_kD4xffx.pdf) that are supposed to apply to all PhD theses submitted to the University of Chicago. 

Does your current format meet all of those guidelines (at least)? Are they the same as the BA requirements? It looks like departments may have specific additional requirements, but this would at least a good place to get started?

**Comment by ejzim** [comment]
Hi
I looked at the PDF and they are slightly more extensive than the BA guidelines. However, the template I have submitted already conforms to these requirements (they appear to be pretty similar to the Harvard requirements, actually).

Best, cheers, etc -Evan via iPhone
On Sat, Jul 30, 2016 at 20:22, Michael Pacer <notifications@github.com> wrote:
@ejzim [https://github.com/ejzim]

It looks like this page at the Chicago library site for dissertations [https://www.lib.uchicago.edu/research/scholar/phd/students/checklist/] links to this pdf on formatting requirements from 2011 [https://www.lib.uchicago.edu/documents/788/booklet2011_kD4xffx.pdf] that are supposed to apply to all PhD theses submitted to the University of Chicago.

Does your current format meet all of those guidelines (at least)? Are they the same as the BA requirements? It looks like departments may have specific additional requirements, but this would at least a good place to get started?

**Pull request merged**
